# Alt Küme Üzerinde İşlem Yapmak

In [2]:
import numpy as np

In [3]:
a = np.random.randint(10, size=(5,5))

In [4]:
a

array([[8, 6, 4, 4, 1],
       [5, 5, 9, 0, 3],
       [2, 8, 7, 5, 8],
       [6, 1, 3, 8, 9],
       [4, 3, 3, 4, 3]])

In [5]:
alt_a = a[0:3,0:2]

In [6]:
alt_a

array([[8, 6],
       [5, 5],
       [2, 8]])

In [7]:
alt_a [0,0] = 9999
alt_a [1,1] = 8888

In [8]:
alt_a

array([[9999,    6],
       [   5, 8888],
       [   2,    8]])

In [9]:
a

array([[9999,    6,    4,    4,    1],
       [   5, 8888,    9,    0,    3],
       [   2,    8,    7,    5,    8],
       [   6,    1,    3,    8,    9],
       [   4,    3,    3,    4,    3]])

In [10]:
m = np.random.randint(10, size=(5,5))

In [11]:
m

array([[5, 3, 5, 2, 0],
       [7, 5, 3, 0, 5],
       [0, 4, 4, 3, 0],
       [3, 4, 7, 1, 8],
       [6, 3, 5, 5, 5]])

In [15]:
alt_b = m[0:3,0:2].copy()

In [16]:
alt_b

array([[5, 3],
       [7, 5],
       [0, 4]])

In [17]:
alt_b [0,0] = 1111
alt_b [1,1] = 2222

In [18]:
alt_b

array([[1111,    3],
       [   7, 2222],
       [   0,    4]])

In [19]:
m

array([[5, 3, 5, 2, 0],
       [7, 5, 3, 0, 5],
       [0, 4, 4, 3, 0],
       [3, 4, 7, 1, 8],
       [6, 3, 5, 5, 5]])