# NumPy Array'i Oluşturmak

In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
a=np.array([1,2,3,4,5])

In [4]:
type(a)

numpy.ndarray

In [7]:
np.array([3.14,5,2,13],dtype="int")

array([ 3,  5,  2, 13])

In [ ]:
#sifirdan array olusturma

In [8]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [10]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [11]:
np.arange(0,31, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [12]:
np.linspace(0,1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [14]:
np.random.normal(10, 4, (3,4))

array([[18.09927503, 14.5316707 , 10.94348614, 13.81171132],
       [ 8.66983407, 11.84448538,  4.96241465,  8.10503643],
       [12.45284889, 11.95697841,  6.89711944, 16.33682547]])

In [17]:
np.random.randint(0,10 , (3,3))

array([[9, 3, 8],
       [3, 4, 4],
       [3, 7, 8]])