# Slicing ile Elemanlara Erişmek (Array Alt Kümesine Erişmek)

In [1]:
import numpy as np

In [2]:
a = np.arange(20,30)

In [3]:
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [4]:
a[0:3]

array([20, 21, 22])

In [5]:
a[:3]

array([20, 21, 22])

In [6]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [8]:
a[0::2]

array([20, 22, 24, 26, 28])

In [9]:
#iki boyutlu slice işlemleri

In [12]:
m = np.random.randint(10 , size = (5,5))

In [13]:
m

array([[9, 5, 4, 3, 1],
       [5, 2, 4, 8, 2],
       [8, 1, 0, 9, 3],
       [5, 2, 2, 7, 1],
       [8, 0, 9, 6, 6]])

In [14]:
m[:,0]

array([9, 5, 8, 5, 8])

In [15]:
m[:,1]

array([5, 2, 1, 2, 0])

In [16]:
m[0,:]

array([9, 5, 4, 3, 1])

In [17]:
m[1,:]

array([5, 2, 4, 8, 2])

In [18]:
m[0:2,0:3]

array([[9, 5, 4],
       [5, 2, 4]])

In [19]:
m[:,0:2]

array([[9, 5],
       [5, 2],
       [8, 1],
       [5, 2],
       [8, 0]])

In [20]:
m[1:3,0:2]

array([[5, 2],
       [8, 1]])