# Array Sıralama (Sorting)

In [1]:
import numpy as np

In [2]:
v = np.array([2,1,4,3,5])

In [3]:
v

array([2, 1, 4, 3, 5])

In [4]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [5]:
v

array([2, 1, 4, 3, 5])

In [6]:
v.sort()

In [7]:
v

array([1, 2, 3, 4, 5])

In [9]:
#iki boyut

In [18]:
m = np.random.normal(20,5, (3,3))

In [19]:
m

array([[26.39545049, 22.40738108, 24.82470078],
       [21.65000241, 23.44893794, 23.92219739],
       [16.67160088, 25.79449515, 17.05256838]])

In [20]:
np.sort (m , axis = 1)

array([[22.40738108, 24.82470078, 26.39545049],
       [21.65000241, 23.44893794, 23.92219739],
       [16.67160088, 17.05256838, 25.79449515]])

In [22]:
np.sort (m , axis = 0)

array([[16.67160088, 22.40738108, 17.05256838],
       [21.65000241, 23.44893794, 23.92219739],
       [26.39545049, 25.79449515, 24.82470078]])