# Array Ayırma (Splitting)

In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,99,99,3,2,1])

In [3]:
np.split(x, [3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [4]:
a,b,c = np.split(x, [3,5])

In [5]:
a

array([1, 2, 3])

In [6]:
b

array([99, 99])

In [7]:
c

array([3, 2, 1])

In [8]:
#iki boyut

In [9]:
m = np.arange(16).reshape(4,4)

In [10]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [11]:
np.vsplit(m, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [12]:
ust,alt = np.vsplit(m, [2])

In [13]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [14]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [15]:
np.hsplit(m, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [19]:
sag,sol = np.hsplit(m, [2])

In [20]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [21]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])