# Index ile Elemananlara Erişmek

In [1]:
import numpy as np

In [2]:
a = np.random.randint (10, size = 10)

In [3]:
a

array([8, 2, 7, 4, 6, 5, 4, 6, 4, 7])

In [4]:
a[0]

8

In [5]:
m = np.random.randint (10, size = (3,4))

In [6]:
m

array([[4, 4, 3, 5],
       [4, 4, 8, 2],
       [6, 3, 8, 2]])

In [7]:
m[0,0]

4

In [8]:
m[2,1]

3

In [9]:
m[2,2] = 32

In [10]:
m

array([[ 4,  4,  3,  5],
       [ 4,  4,  8,  2],
       [ 6,  3, 32,  2]])